In [2]:
import cv2

In [3]:
image = cv2.imread('image.png',0)

In [4]:
#display the image

In [5]:
cv2.imshow('image',image)   # the title and path to image
cv2.waitKey(0)              # Waits for the next key to be pressed
cv2.destroyAllWindows()

In [6]:
cv2.imwrite('imageIngrayScale.png',image)

True

In [7]:
import numpy as np
import cv2 as cv
face_cascade = cv.CascadeClassifier('haarcascade_frontalface_default.xml')
eye_cascade = cv.CascadeClassifier('haarcascade_eye.xml')
img = cv.imread('sachin.jpg')
gray = cv.cvtColor(img, cv.COLOR_BGR2GRAY)

error: OpenCV(3.4.3) C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:181: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'


In [8]:
video =  cv2.VideoCapture(0)

check , frame = video.read()
print(check)
print(frame)


cv2.imshow("Capturing",img)
video.release()

True
[[[ 81  83  78]
  [ 75  76  71]
  [ 70  77  69]
  ...
  [162 136 140]
  [156 139 143]
  [152 135 139]]

 [[ 84  82  80]
  [ 79  77  75]
  [ 73  74  72]
  ...
  [158 133 133]
  [149 135 136]
  [149 135 136]]

 [[ 79  79  81]
  [ 75  74  76]
  [ 71  71  71]
  ...
  [157 138 124]
  [152 135 128]
  [152 135 128]]

 ...

 [[248 242 255]
  [247 241 255]
  [249 241 255]
  ...
  [206 200 203]
  [206 202 209]
  [205 201 208]]

 [[248 243 255]
  [246 240 255]
  [247 239 255]
  ...
  [211 200 208]
  [205 202 216]
  [207 204 218]]

 [[248 244 255]
  [244 240 255]
  [244 239 255]
  ...
  [207 201 208]
  [209 205 203]
  [206 201 200]]]


In [1]:
import cv2
import numpy as np

cap = cv2.VideoCapture(0)
while True:
    ret,frame = cap.read()
    cv2.imshow("Video output",frame)
    k = cv2.waitKey(10)& 0xff
    if k == 27:
        break
cap.release()
cv2.destroyAllWindows()